# Generated by Django 5.1.1 on 2024-09-15 04:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='kelas_siswa',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='nama_siswa',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='name_product',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='Unknown', max_length=400),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default='Unknown'),
        ),
    ]
