# Generated by Django 5.1.1 on 2024-09-17 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_product_name_product_kelas_siswa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='kelas_siswa',
        ),
        migrations.RemoveField(
            model_name='product',
            name='nama_siswa',
        ),
    ]
