# Generated by Django 5.1.1 on 2024-09-25 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_product_kelas_siswa_remove_product_nama_siswa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='Tambahkan Deskripsi (max: 400 kata)', max_length=400),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_product',
            field=models.CharField(default='Masukan Nama Produk', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default='0'),
        ),
    ]
